MODULE DWConfig;

CONST
  (* Versia: *)
  DarkWoods1*  = TRUE;
  DarkWoods2*  = FALSE;

  (* Screen: *)
  ScreenWidth* = 32;

  (* Title: *)
  SkullX*      =  1;
  SkullY*      =  2;
  FrameX*      = 14;
  FrameY*      =  4;
  FrameWidth*  = 17;
  FrameHeight* =  5;
  DarkWoodsX*  = 17;
  DarkWoodsY*  =  5;
  JockeX*      =  9;
  JockeY*      = 14;
  MenuLineX*   =  1;
  MenuLineY*   = 20;
  QuitMenuX*   =  0;
  QuitMenuY*   =  7;
  QuitTitlePos*   =  QuitMenuX + 1;
  QuitMenuWidth*  = 30;
  QuitMenuHeight* =  4;
  QuitThanxX*     =  3;
  QuitThanxY*     =  2;

END DWConfig.