MODULE DWColors;

IMPORT Console;

CONST
  Eduin   * = Console.YellowOnBlack;
  Tree    * = Console.GreenOnBlack;
  Bush    * = Console.LGreenOnBlack;
  Wall    * = Console.WhiteOnBlack;
  Door    * = Console.WhiteOnBlack;
  Bow     * = Console.LWhiteOnBlack;
  Arrows  * = Console.LWhiteOnBlack;
  Potion  * = Console.LRedOnBlack;
  Key     * = Console.YellowOnBlack;
  Gold    * = Console.YellowOnBlack;
  Jewel   * = Console.YellowOnBlack;
  Firewall* = Console.LRedOnBlack;
  Trap    * = Console.RedOnBlack;
  Orc     * = Console.RedOnBlack;
  Troll   * = Console.RedOnBlack;
  RingOfFire* = Console.BlueOnBlack;

END DWColors.