MODULE DW2Config;

CONST
  (* Versia: *)
  DarkWoods1*  = TRUE;
  DarkWoods2*  = FALSE;

  (* Screen: *)
  ScreenWidth* = 40;

  (* Title: *)
  TitleX*      =  3;
  TitleY*      =  2;
  FrameX*      = 16;
  FrameY*      =  4;
  FrameWidth*  = 20;
  FrameHeight* =  5;
  DarkWoodsX*  = 21;
  DarkWoodsY*  =  5;
  JockeX*      = 12;
  JockeY*      = 14;
  MenuLineX*   =  2;
  MenuLineY*   = 20;

END DW2Config.