MODULE DWConfig;

CONST
  (* Versia: *)
  DarkWoods1*  = TRUE;
  DarkWoods2*  = FALSE;

  (* Screen: *)
  ScreenWidth* = 40;

  (* Title: *)
  SkullX*      =  3;
  SkullY*      =  2;
  FrameX*      = 16;
  FrameY*      =  4;
  FrameWidth*  = 20;
  FrameHeight* =  5;
  DarkWoodsX*  = 21;
  DarkWoodsY*  =  5;
  JockeX*      = 12;
  JockeY*      = 14;
  MenuLineX*   =  2;
  MenuLineY*   = 20;
  QuitMenuX*   =  2;
  QuitMenuY*   =  7;
  QuitTitlePos*   =  QuitMenuX + 3;
  QuitMenuWidth*  = 32;
  QuitMenuHeight* =  5;
  QuitThanxX*     =  3;
  QuitThanxY*     =  2;

  MapXOffset*     =  5;
  MapYOffset*     =  1;
  MapWidth*       = 30;
  MapHeight*      = 15;

  DelayBlinkEffect* = 60;

END DWConfig.